//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_hunger2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accepted
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accepted()
        {
            this.Colleacts = new HashSet<Colleact>();
        }
    
        public int ResId { get; set; }
        public int Nid { get; set; }
        public int Eid { get; set; }
        public int OrderId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual NGO NGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colleact> Colleacts { get; set; }
    }
}
