//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_hunger2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colleact
    {
        public int ResId { get; set; }
        public string PreTime { get; set; }
        public string Status { get; set; }
    
        public virtual Accepted Accepted { get; set; }
        public virtual Resturent Resturent { get; set; }
    }
}
