//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_hunger2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zero_HungerEntities : DbContext
    {
        public Zero_HungerEntities()
            : base("name=Zero_HungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accepted> Accepteds { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<NGO> NGOes { get; set; }
        public virtual DbSet<Resturent> Resturents { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Colleact> Colleacts { get; set; }
    }
}
